name: Build

on:
  push:
    branches: [ master ]
  #schedule:
  #  - cron: '0 0 * * *'  # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Config
        run: ./configure
