name: Build

on:
  push:
    branches: [ master ]
  #schedule:
  #  - cron: '0 0 * * *'  # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Config
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==5.3.0
          sudo apt update
          sudo apt install libglib2.0-dev
          QEMU_BUILD_DIR = /tmp/zeus/qemu
          mkdir -p $QEMU_BUILD_DIR
          ./configure \
          --disable-docs --without-default-features \
          --disable-curses --disable-opengl --disable-sdl --disable-glusterfs --disable-sdl-image \
          --disable-vnc --disable-vnc-jpeg --disable-vnc-sasl --disable-virglrenderer \
          --disable-xkbcommon --disable-gtk --disable-auth-pam --disable-bzip2 \
          --target-list=zeus-softmmu \
          cd $QEMU_BUILD_DIR && make -j8




