name: Build

on:
  push:
    branches: [ master ]
  #schedule:
  #  - cron: '0 0 * * *'  # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Config
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==5.3.0
          sudo apt update
          sudo apt install libglib2.0-dev
          ./configure



